# Generated by Django 3.2.9 on 2021-12-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Car', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Kilometers', models.IntegerField()),
                ('Model', models.IntegerField()),
                ('Problem', models.CharField(max_length=1000)),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
